# ============================================================================
# 02_evi_epoch1.R
# Epoch 1 (baseline) pipeline: Landsat 5/7, Jan-Mar window 2008-2010.
# Download -> crop -> QA mask -> EVI -> local harmonization -> composite.
# ============================================================================
#
# REQUIRES: 00_config.R sourced first, and 01_harmonization.R already run
#           (01_harmonization_results.R present at the repository root).
#
# Scene list source: USGS EarthExplorer export, study Path/Row, 11 scenes.
# STAC identifiers strip the second (processing-date) timestamp present in
# USGS product IDs; e.g. LE07_L2SP_009053_20080116_20200913_02_T1 (USGS)
# corresponds to LE07_L2SP_009053_20080116_02_T1 (STAC).
#
#   LE07_L2SP_009053_20080116_02_T1   2008-01-16   cloud 1.00%
#   LE07_L2SP_009053_20080201_02_T1   2008-02-01   cloud 2.00%
#   LE07_L2SP_009053_20080304_02_T1   2008-03-04   cloud 36.00%
#   LE07_L2SP_009053_20080320_02_T1   2008-03-20   cloud 5.00%
#   LE07_L2SP_009053_20090219_02_T1   2009-02-19   cloud 22.00%
#   LE07_L2SP_009053_20090307_02_T1   2009-03-07   cloud 5.00%
#   LE07_L2SP_009053_20090323_02_T1   2009-03-23   cloud 13.00%
#   LE07_L2SP_009053_20100105_02_T1   2010-01-05   cloud 3.00%
#   LE07_L2SP_009053_20100121_02_T1   2010-01-21   cloud 1.00%
#   LE07_L2SP_009053_20100310_02_T1   2010-03-10   cloud 27.00%
#   LE07_L2SP_009053_20100326_02_T1   2010-03-26   cloud 41.00%
#
# EVI: 2.5 * (NIR - Red) / (NIR + 6*Red - 7.5*Blue + 1), clamped [-1, 1].
# Local harmonization coefficients are sourced from
# 01_harmonization_results.R (generated by 01_harmonization.R), not
# re-typed here, so the two scripts cannot silently disagree.
#
# Output: per-scene native and harmonized EVI rasters, a valid-pixel log
# (its total is the pixel-count target used by 03_evi_epoch2.R), and the
# harmonized Epoch 1 composite (pixel-wise mean).
#
# DEPENDENCIES: rstac, terra, sf
# ============================================================================

source("00_config.R")
source("01_harmonization_results.R")

library(rstac)
library(terra)
library(sf)

epoch1_scenes <- c(
  "LE07_L2SP_009053_20080116_02_T1",
  "LE07_L2SP_009053_20080201_02_T1",
  "LE07_L2SP_009053_20080304_02_T1",
  "LE07_L2SP_009053_20080320_02_T1",
  "LE07_L2SP_009053_20090219_02_T1",
  "LE07_L2SP_009053_20090307_02_T1",
  "LE07_L2SP_009053_20090323_02_T1",
  "LE07_L2SP_009053_20100105_02_T1",
  "LE07_L2SP_009053_20100121_02_T1",
  "LE07_L2SP_009053_20100310_02_T1",
  "LE07_L2SP_009053_20100326_02_T1"
)

study_area <- vect(STUDY_AREA_SHP)
aoi_wgs    <- st_as_sfc(st_bbox(BBOX_WGS84, crs = 4326))

cat("Using local harmonization: EVI_h =", LOCAL_HARMONIZATION_INTERCEPT,
    "+", LOCAL_HARMONIZATION_SLOPE, "* EVI_native",
    "(R2 =", LOCAL_HARMONIZATION_R2, ", n =", LOCAL_HARMONIZATION_N, ")\n\n")

# ----------------------------------------------------------------------------
# 1. Download: Blue, Red, NIR, QA_PIXEL per scene
# ----------------------------------------------------------------------------

fetch_item_by_id <- function(scene_id) {
  res <- stac("https://planetarycomputer.microsoft.com/api/stac/v1") |>
    stac_search(collections = "landsat-c2-l2", ids = scene_id) |>
    get_request() |>
    items_sign(sign_fn = sign_planetary_computer())
  if (length(res$features) == 0) return(NULL)
  res$features[[1]]
}

get_asset_url <- function(item, name) {
  href <- item$assets[[name]]$href
  if (is.null(href) || !nzchar(href)) NULL else href
}

download_asset <- function(scene_id, asset_name, out_name, out_dir) {
  out_file <- file.path(out_dir, paste0(scene_id, "_", out_name, ".tif"))
  if (file.exists(out_file) && file.size(out_file) > 1000) {
    cat("    [skip]", out_name, "\n"); return(out_file)
  }
  item <- fetch_item_by_id(scene_id)
  if (is.null(item)) { cat("    ERROR: scene not found\n"); return(NULL) }
  url <- get_asset_url(item, asset_name)
  if (is.null(url)) { cat("    ERROR: asset '", asset_name, "' not available\n", sep=""); return(NULL) }
  ok <- tryCatch({
    r <- rast(paste0("/vsicurl/", url))
    aoi_utm <- st_transform(aoi_wgs, crs(r))
    r_crop <- crop(r, vect(aoi_utm))
    writeRaster(r_crop, out_file, overwrite = TRUE, gdal = c("COMPRESS=LZW"))
    cat("    OK:", out_name, "\n"); TRUE
  }, error = function(e) { cat("    ERROR:", conditionMessage(e), "\n"); FALSE })
  if (ok) out_file else NULL
}

cat("=== STEP 1: DOWNLOAD ===\n\n")
for (scene_id in epoch1_scenes) {
  cat(scene_id, ":\n")
  download_asset(scene_id, "blue", "BLUE", DIR_EVI_RAW)
  download_asset(scene_id, "red", "RED", DIR_EVI_RAW)
  download_asset(scene_id, "nir08", "NIR", DIR_EVI_RAW)
  download_asset(scene_id, "qa_pixel", "QA", DIR_EVI_RAW)
  cat("\n")
}

# ----------------------------------------------------------------------------
# 2-5. Per scene: crop to study area, mask QA==5440, compute native EVI,
#      apply local harmonization, log valid-pixel counts.
# ----------------------------------------------------------------------------

scale_sr <- function(dn) clamp(dn * SR_SCALE + SR_OFFSET, 0, 1)

compute_evi <- function(nir, red, blue) {
  evi <- 2.5 * (nir - red) / (nir + 6 * red - 7.5 * blue + 1)
  clamp(evi, -1, 1)
}

cat("=== STEPS 2-5: CROP, MASK, EVI, HARMONIZATION, PIXEL COUNT ===\n\n")

evi_native_list     <- list()
evi_harmonized_list <- list()
pixel_log <- data.frame()

for (scene_id in epoch1_scenes) {
  cat("Processing:", scene_id, "\n")

  blue_f <- file.path(DIR_EVI_RAW, paste0(scene_id, "_BLUE.tif"))
  red_f  <- file.path(DIR_EVI_RAW, paste0(scene_id, "_RED.tif"))
  nir_f  <- file.path(DIR_EVI_RAW, paste0(scene_id, "_NIR.tif"))
  qa_f   <- file.path(DIR_EVI_RAW, paste0(scene_id, "_QA.tif"))

  if (!all(file.exists(c(blue_f, red_f, nir_f, qa_f)))) {
    cat("  SKIP: missing downloaded files\n\n")
    next
  }

  blue <- rast(blue_f); red <- rast(red_f); nir <- rast(nir_f); qa <- rast(qa_f)

  study_area_r <- if (crs(study_area) != crs(qa)) project(study_area, crs(qa)) else study_area
  blue_c <- crop(blue, study_area_r, mask = TRUE)
  red_c  <- crop(red,  study_area_r, mask = TRUE)
  nir_c  <- crop(nir,  study_area_r, mask = TRUE)
  qa_c   <- crop(qa,   study_area_r, mask = TRUE)

  qa_mask <- qa_c == QA_GOOD_VALUE_ETM
  n_valid <- global(qa_mask, "sum", na.rm = TRUE)[1, 1]
  n_total <- global(!is.na(qa_c), "sum", na.rm = TRUE)[1, 1]

  cat("  Valid pixels (QA==", QA_GOOD_VALUE_ETM, "):", n_valid, "/", n_total, "\n", sep = "")

  pixel_log <- rbind(pixel_log, data.frame(
    scene_id = scene_id, n_valid = n_valid, n_total = n_total
  ))

  blue_sr <- scale_sr(blue_c); red_sr <- scale_sr(red_c); nir_sr <- scale_sr(nir_c)
  blue_m <- ifel(qa_mask, blue_sr, NA)
  red_m  <- ifel(qa_mask, red_sr,  NA)
  nir_m  <- ifel(qa_mask, nir_sr,  NA)

  evi_native <- compute_evi(nir_m, red_m, blue_m)
  names(evi_native) <- scene_id

  evi_harmonized <- LOCAL_HARMONIZATION_INTERCEPT + LOCAL_HARMONIZATION_SLOPE * evi_native
  evi_harmonized <- clamp(evi_harmonized, -1, 1)
  names(evi_harmonized) <- scene_id

  writeRaster(evi_native, file.path(DIR_EVI_OUT, paste0(scene_id, "_EVI_native.tif")),
              overwrite = TRUE, gdal = c("COMPRESS=LZW"))
  writeRaster(evi_harmonized, file.path(DIR_EVI_OUT, paste0(scene_id, "_EVI_harmonized.tif")),
              overwrite = TRUE, gdal = c("COMPRESS=LZW"))

  evi_native_list[[scene_id]]     <- evi_native
  evi_harmonized_list[[scene_id]] <- evi_harmonized
  cat("\n")
}

N_target <- sum(pixel_log$n_valid, na.rm = TRUE)

cat("=== VALID-PIXEL LOG ===\n")
print(pixel_log, row.names = FALSE)
cat("\nN_target (total valid pixels, Epoch 1):", N_target, "\n\n")

write.csv(pixel_log, file.path(DIR_EVI, "epoch1_pixel_log.csv"), row.names = FALSE)

# ----------------------------------------------------------------------------
# Composites: native and harmonized, pixel-wise mean across all scenes
# ----------------------------------------------------------------------------

build_composite <- function(evi_list, out_name) {
  ref <- evi_list[[1]]
  aligned <- lapply(evi_list, function(r) {
    if (!compareGeom(r, ref, stopOnError = FALSE)) resample(r, ref, method = "bilinear") else r
  })
  stack <- rast(aligned)
  comp <- mean(stack, na.rm = TRUE)
  names(comp) <- out_name
  comp
}

epoch1_native_mean     <- build_composite(evi_native_list, "EPOCH1_EVI_MEAN_native")
epoch1_harmonized_mean <- build_composite(evi_harmonized_list, "EPOCH1_EVI_MEAN_harmonized")

writeRaster(epoch1_native_mean, file.path(DIR_EVI_OUT, "EPOCH1_EVI_MEAN_native.tif"),
            overwrite = TRUE, gdal = c("COMPRESS=LZW"))
writeRaster(epoch1_harmonized_mean, file.path(DIR_EVI_OUT, "EPOCH1_EVI_MEAN_harmonized.tif"),
            overwrite = TRUE, gdal = c("COMPRESS=LZW"))

# Write N_target to a small results file, mirroring the pattern used by
# 01_harmonization.R, so 03_evi_epoch2.R can source it directly.
writeLines(
  c("# AUTO-GENERATED by 02_evi_epoch1.R -- do not edit by hand.",
    sprintf("EPOCH1_N_TARGET <- %d", N_target)),
  file.path(DIR_ROOT, "02_evi_epoch1_results.R")
)

cat("=== COMPOSITE STATS ===\n")
cat("Native:\n");     print(global(epoch1_native_mean, c("min","max","mean","sd"), na.rm = TRUE))
cat("Harmonized:\n"); print(global(epoch1_harmonized_mean, c("min","max","mean","sd"), na.rm = TRUE))

cat("\n02_evi_epoch1.R complete. N_target written to 02_evi_epoch1_results.R\n")